### PR TITLE
Move Bower to dependencies

### PR DESCRIPTION
**Pull request by jparmenter**
Last one 😄

### CODE REVIEW

**Comment by jsdevel** [comment]
How come?  Wouldn't it work just fine in dev deps?

**Comment by jparmenter** [comment]
I forget with NPM but after I brought in the new version the `node_modules` weren't getting installed with `yarn`. My fork brought in bower just fine.

We just brought webpack into master and with the new version this has been coming up a few times.

**Comment by jsdevel** [comment]
I'm still struggling to understand why you need it though.  Is there a command that fails?  I'd rather not make bower a prod dependency in an npm package.

**Comment by jparmenter** [comment]
Yeah the `bower install` fails when we `npm install` even with the `devDependencies`. It works when it's a prod dependency.

**Comment by jsdevel** [comment]
Oh, I see what's happening.  You'll need to add bower as a dependency in your project's package.json file.

**Pull request closed without merging**
